function [MRTimes2, G1targetvolumemL, G1FCO1, G1FO1, G2FCO1, G2FO1, G1measuredbreathmL, G2measuredbreathmL, BlendermeasuredtotalmL, BlendermeasuredCO2mL, BlendermeasuredO2mL, BlendermeasuredS1mL, BlendermeasuredS2mL] = import_VSGD(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [MRTIMES2, G1TARGETVOLUMEML, G1FCO1, G1FO1, G2FCO1, G2FO1,
%  G1MEASUREDBREATHML, G2MEASUREDBREATHML, BLENDERMEASUREDTOTALML,
%  BLENDERMEASUREDCO2ML, BLENDERMEASUREDO2ML, BLENDERMEASUREDS1ML,
%  BLENDERMEASUREDS2ML] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [MRTIMES2, G1TARGETVOLUMEML, G1FCO1, G1FO1, G2FCO1, G2FO1,
%  G1MEASUREDBREATHML, G2MEASUREDBREATHML, BLENDERMEASUREDTOTALML,
%  BLENDERMEASUREDCO2ML, BLENDERMEASUREDO2ML, BLENDERMEASUREDS1ML,
%  BLENDERMEASUREDS2ML] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [MRTimes2, G1targetvolumemL, G1FCO1, G1FO1, G2FCO1, G2FO1, G1measuredbreathmL, G2measuredbreathmL, BlendermeasuredtotalmL, BlendermeasuredCO2mL, BlendermeasuredO2mL, BlendermeasuredS1mL, BlendermeasuredS2mL] = importfile("C:\Users\abhogal\Documents\DATA\MRI_data\APRICOT\APC005\respiraccttraces\2020-01-14 02;42;39 (APC005)\VSGD.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Jan-2020 21:52:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["MRTimes2", "G1targetvolumemL", "G1FCO1", "G1FO1", "G2FCO1", "G2FO1", "G1measuredbreathmL", "G2measuredbreathmL", "BlendermeasuredtotalmL", "BlendermeasuredCO2mL", "BlendermeasuredO2mL", "BlendermeasuredS1mL", "BlendermeasuredS2mL"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
MRTimes2 = tbl.MRTimes2;
G1targetvolumemL = tbl.G1targetvolumemL;
G1FCO1 = tbl.G1FCO1;
G1FO1 = tbl.G1FO1;
G2FCO1 = tbl.G2FCO1;
G2FO1 = tbl.G2FO1;
G1measuredbreathmL = tbl.G1measuredbreathmL;
G2measuredbreathmL = tbl.G2measuredbreathmL;
BlendermeasuredtotalmL = tbl.BlendermeasuredtotalmL;
BlendermeasuredCO2mL = tbl.BlendermeasuredCO2mL;
BlendermeasuredO2mL = tbl.BlendermeasuredO2mL;
BlendermeasuredS1mL = tbl.BlendermeasuredS1mL;
BlendermeasuredS2mL = tbl.BlendermeasuredS2mL;
end