function [MRTimes3, CtrlRoomTimes, Event] = import_Events(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [MRTIMES3, CTRLROOMTIMES, EVENT] = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as column vectors.
%
%  [MRTIMES3, CTRLROOMTIMES, EVENT] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [MRTimes3, CtrlRoomTimes, Event] = importfile("C:\Users\abhogal\Documents\DATA\MRI_data\APRICOT\APC005\respiraccttraces\2020-01-14 02;42;39 (APC005)\Events.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Jan-2020 22:10:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["MRTimes3", "CtrlRoomTimes", "Event"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Event", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Event", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
MRTimes3 = tbl.MRTimes3;
CtrlRoomTimes = tbl.CtrlRoomTimes;
Event = tbl.Event;
end