function [MRTimes1, LocalTimeUTC1, PO2mmHg1, PCO2mmHg1, PBarommHg1, PMouthmmH2O, RawTimestamps, FlowMouthmLmin, FlowS1mLmin, FlowS2mLmin, BreathPhase] = import_RGM_V2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [MRTIMES1, LOCALTIMEUTC1, PO2MMHG1, PCO2MMHG1, PBAROMMHG1,
%  PMOUTHMMH2O, RAWTIMESTAMPS, FLOWMOUTHMLMIN, FLOWS1MLMIN, FLOWS2MLMIN,
%  BREATHPHASE] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [MRTIMES1, LOCALTIMEUTC1, PO2MMHG1, PCO2MMHG1, PBAROMMHG1,
%  PMOUTHMMH2O, RAWTIMESTAMPS, FLOWMOUTHMLMIN, FLOWS1MLMIN, FLOWS2MLMIN,
%  BREATHPHASE] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [MRTimes1, LocalTimeUTC1, PO2mmHg1, PCO2mmHg1, PBarommHg1, PMouthmmH2O, RawTimestamps, FlowMouthmLmin, FlowS1mLmin, FlowS2mLmin, BreathPhase] = importfile("G:\SMART_MICRO\SMP000\traces\RGM.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-May-2025 13:36:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["MRTimes1", "LocalTimeUTC1", "PO2mmHg1", "PCO2mmHg1", "PBarommHg1", "PMouthmmH2O", "RawTimestamps", "FlowMouthmLmin", "FlowS1mLmin", "FlowS2mLmin", "BreathPhase", "Var12"];
opts.SelectedVariableNames = ["MRTimes1", "LocalTimeUTC1", "PO2mmHg1", "PCO2mmHg1", "PBarommHg1", "PMouthmmH2O", "RawTimestamps", "FlowMouthmLmin", "FlowS1mLmin", "FlowS2mLmin", "BreathPhase"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var12", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["BreathPhase", "Var12"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "LocalTimeUTC1", "InputFormat", "HH:mm:ss");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
MRTimes1 = tbl.MRTimes1;
LocalTimeUTC1 = tbl.LocalTimeUTC1;
PO2mmHg1 = tbl.PO2mmHg1;
PCO2mmHg1 = tbl.PCO2mmHg1;
PBarommHg1 = tbl.PBarommHg1;
PMouthmmH2O = tbl.PMouthmmH2O;
RawTimestamps = tbl.RawTimestamps;
FlowMouthmLmin = tbl.FlowMouthmLmin;
FlowS1mLmin = tbl.FlowS1mLmin;
FlowS2mLmin = tbl.FlowS2mLmin;
BreathPhase = tbl.BreathPhase;
end