function [MRTimes1,PO2mmHg1,PCO2mmHg1,PBarommHg1,PMouthmmH2O,FlowMouthmLmin,FlowS1mLmin,FlowS2mLmin,BreathPhase] = import_RGM(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [MRTIMES1,PO2MMHG1,PCO2MMHG1,PBAROMMHG1,PMOUTHMMH2O,FLOWMOUTHMLMIN,FLOWS1MLMIN,FLOWS2MLMIN,BREATHPHASE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [MRTIMES1,PO2MMHG1,PCO2MMHG1,PBAROMMHG1,PMOUTHMMH2O,FLOWMOUTHMLMIN,FLOWS1MLMIN,FLOWS2MLMIN,BREATHPHASE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [MRTimes1,PO2mmHg1,PCO2mmHg1,PBarommHg1,PMouthmmH2O,FlowMouthmLmin,FlowS1mLmin,FlowS2mLmin,BreathPhase] = importfile('RGM.txt',2, 189278);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/07/02 09:43:06

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
MRTimes1 = dataArray{:, 1};
PO2mmHg1 = dataArray{:, 2};
PCO2mmHg1 = dataArray{:, 3};
PBarommHg1 = dataArray{:, 4};
PMouthmmH2O = dataArray{:, 5};
FlowMouthmLmin = dataArray{:, 6};
FlowS1mLmin = dataArray{:, 7};
FlowS2mLmin = dataArray{:, 8};
BreathPhase = dataArray{:, 9};


