function [MRTimes1, LocalTimeUTC1, CtrlRoomTimes, Event] = import_Events_V2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [MRTIMES1, LOCALTIMEUTC1, CTRLROOMTIMES, EVENT] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [MRTIMES1, LOCALTIMEUTC1, CTRLROOMTIMES, EVENT] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [MRTimes1, LocalTimeUTC1, CtrlRoomTimes, Event] = importfile("G:\SMART_MICRO\SMP000\traces\Events.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-May-2025 14:04:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["MRTimes1", "LocalTimeUTC1", "CtrlRoomTimes", "Event"];
opts.VariableTypes = ["double", "datetime", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Event", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Event", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "LocalTimeUTC1", "InputFormat", "HH:mm:ss");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
MRTimes1 = tbl.MRTimes1;
LocalTimeUTC1 = tbl.LocalTimeUTC1;
CtrlRoomTimes = tbl.CtrlRoomTimes;
Event = tbl.Event;
end